package enums;

public enum Escolaridade {
	ENSINO_FUNDAMENTAL_INCOMPLETO, ENSINO_FUNDAMENTAL_COMPLETO, ENSINO_MEDIO_COMPLETO, ENSINO_MEDIO_INCOMPLETO,
	CURSO_SUPERIOR_COMPLETO, CURSO_SUPERIOR_INCOMPLETO,
}
